### ISSUE TITLE
ranger.vim pollutes buffers with directories

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/ranger.vim#10]
This makes cycling through buffers annoying, as ranger is continually reopened when you hit a directory. These should be deleted automatically after every ranger command.

**Comment by hsanson** [comment]
I noted this issue in neovim while writing PR #9. After countless hours in the vim help files I managed to avoid polluting the buffers with this snippet:

```
     if bufnr('%') != bufnr('#')
         setl bufhidden=delete | buffer! #
     else
         enew | bdelete! #
      endif
```

What this does is:

 1. Check if there is a previous ('#') buffer that is not the current one ('%')
 2. In case there is a previous buffer:
      2.1  Set current buffer local property bufhidden to delete. This means that when we change to another buffer, the current one will be deleted. Usually this will be the ranger buffer that pollutes the space. And since we set it locally (setl) it only affects the current buffer.
      2.2 Then change to the previous buffer with: buffer! #. This will open any previous buffer available and remove the ranger buffer.
  3. I case there are no previous buffers. Usually because there is only one open buffer.
      3.1  Create a new buffer with enew
      3.2  Delete the previous buffer with bdelete! #.

You can verify in neovim that this keeps the buffer list clean Hopefully this can be used too in vim.

**Comment by rafaqz** [comment]
Thanks, I'll try applying that in vim too.
